version: '3'

services: 
    api:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
           - 8000:8000
     
    web: 
        build: .
        command: python manage.py runserver 127.0.0.1:8000
        ports: 
          -  "8000:8000"